{% set name = "django-orghierarchy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-orghierarchy-{{ version }}.tar.gz
  sha256: 5634da7c9ec70a951607f38a4cbbf8d953464ef56b8b6a7ded85bfecd696b536

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.2
    - django-mptt
    - djangorestframework
    - requests
    - swapper

test:
  imports:
    - django_orghierarchy
  requires:
    - pip

about:
  home: https://github.com/City-of-Helsinki/django-orghierarchy
  summary: Reusable Django application for hierarchical organizations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
